In [1]:
import numpy as np
from numpy.linalg import inv

In [6]:
def least_squares_cuadratic(x_list, y_list):
    matrix = np.zeros((3, 3), np.float32)
    vector = np.zeros((3), np.float32)
    scalar_factor = 100
    x_list = np.true_divide(x_list, scalar_factor) # Escalo para que las sumatorias no se vayan de rango
    y_list = np.true_divide(y_list, scalar_factor)
    matrix[0, 0] = x_list.shape[0]
    matrix[1, 0] = np.sum(x_list)
    matrix[0, 1] = matrix[1, 0]
    x_pow_2 = np.multiply(x_list, x_list)
    matrix[0, 2] = np.sum(x_pow_2)
    matrix[1, 1] = matrix[0, 2]
    matrix[2, 0] = matrix[0, 2]
    x_pow_3 = np.multiply(x_list, x_pow_2)
    matrix[1, 2] = np.sum(x_pow_3)
    matrix[2, 1] = matrix[1, 2]
    matrix[2, 2] = np.sum(np.multiply(x_list, x_pow_3))
    vector[0] = np.sum(y_list)
    vector[1] = np.sum(np.multiply(x_list, y_list))
    vector[2] = np.sum(np.multiply(x_pow_2, y_list))
    matrix_inv = inv(matrix)
    print('matriz inv')
    print(matrix_inv)
    print('vector')
    print(vector)
    # multiplicar matriz con vector A*v
    c = np.dot(matrix_inv[0, 0:3], vector) * scalar_factor
    b = np.dot(matrix_inv[1, 0:3], vector)
    a = np.dot(matrix_inv[2, 0:3], vector) / scalar_factor
    return a, b, c  # Coeficientes: cuadrático, lineal y independiente

In [7]:
x = np.array([12, 9, 17, 34])
y = np.array([36, 85, 14, 5])
# x = np.true_divide(x,100)
# y = np.true_divide(y,100)
a,b,c = least_squares_cuadratic(x,y)
print(x)
print(y)
print('a: ' + str(a) + ' b: ' + str(b) + ' c: ' + str(c))

matriz inv
[[   13.39151  -147.52109   321.25238]
 [ -147.52109  1685.8267  -3734.7961 ]
 [  321.25238 -3734.7961   8407.447  ]]
vector
[1.4      0.1605   0.021895]
[12  9 17 34]
[36 85 14  5]
a: 0.3439958190917969 b: -17.727692 c: 210.47992706298828


In [28]:
a: 0.3439939754296397 b: -17.727582641144494 c: 210.47900279872636

3.4028235e+38